digraph G {
n1 [label="pair"]
n2 [label="pair"]
n3 [label="just_a_variable"]
n2 -> n3 [label="0"]
n4 [label="pair"]
n5 [label="0"]
n4 -> n5 [label="0"]
n6 [label="37"]
n4 -> n6 [label="1"]
n2 -> n4 [label="1"]
n1 -> n2 [label="0"]
n7 [label="just_a_variable"]
n1 -> n7 [label="1"]
}
