digraph G {
n1 [label="pair"]
n2 [label="list"]
n3 [label="pair"]
n4 [label="just_a_variable"]
n3 -> n4 [label="0"]
n5 [label="pair"]
n6 [label="0"]
n5 -> n6 [label="0"]
n7 [label="37"]
n5 -> n7 [label="1"]
n3 -> n5 [label="1"]
n2 -> n3 [label="0"]
n1 -> n2 [label="0"]
n8 [label="just_a_variable"]
n1 -> n8 [label="1"]
}
